# Site settings
title: the Darling lab | computational (meta)genomics
email: aaron.darling@uts.edu.au
description: > # this means to ignore newlines until "baseurl:"
  The Darling lab at the University of Technology Sydney.
  We develop computational and molecular techniques to characterize
  the hidden world of microbes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://darlinglab.org" # the base hostname & protocol for your site
twitter_username: koadman
github_username:  koadman

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from
